{"name": "test_login[performance_glitch_user-secret_sauce]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9914cef90830aba1e3cf7e694c9d4f8a\")>.current_url\n +    where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9914cef90830aba1e3cf7e694c9d4f8a\")> = <tests.test_login.TestLogin object at 0x000001AAAC0DB890>.driver", "trace": "self = <tests.test_login.TestLogin object at 0x000001AAAC0DB890>, username = 'performance_glitch_user'\npassword = 'secret_sauce'\n\n        @pytest.mark.parametrize(\"username, password\", get_login_data())\n        def test_login(self, username, password):\n            login_page = LoginPage(self.driver)\n            login_page.login(username, password)\n    \n            # Replace 'Tester_Name' with the actual tester's name or get it dynamically\n            tester_name = 'Ramya V'\n    \n    # Asserting if the login was successful by checking the URL to ensure it contains \"dashboard\", to update the Excel file with the test result\n    \n            if \"dashboard\" in self.driver.current_url:\n                update_excel(username, password, \"Passed\", tester_name)\n            else:\n                update_excel(username, password, \"Failed\", tester_name)\n    \n>           assert \"dashboard\" in self.driver.current_url\nE           assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE            +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9914cef90830aba1e3cf7e694c9d4f8a\")>.current_url\nE            +    where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9914cef90830aba1e3cf7e694c9d4f8a\")> = <tests.test_login.TestLogin object at 0x000001AAAC0DB890>.driver\n\ntests\\test_login.py:90: AssertionError"}, "parameters": [{"name": "username", "value": "'performance_glitch_user'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1748945620248, "stop": 1748945624506, "uuid": "e7281886-2c43-46fe-a9fe-9c173ebb37d4", "historyId": "fd940444db66ca46d0729de268680527", "testCaseId": "2116f0ad00ab1de0effc54f114dd9496", "fullName": "tests.test_login.TestLogin#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-8HL83QV"}, {"name": "thread", "value": "5916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}